### ISSUE TITLE
exporters: Python Stackdriver Trace Exporter documentation is now outdated

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-website#664]
#### References
https://opencensus.io/exporters/supported-exporters/python/stackdriver/
https://github.com/census-instrumentation/opencensus-website/blob/master/content/exporters/supported-exporters/Python/Stackdriver.md

#### 1. Stackdriver Exporter API is not documented:
https://census-instrumentation.github.io/opencensus-python/trace/api/stackdriver_exporter.html

#### 2. Imports are incorrect
Is:
```
from opencensus.trace.exporters import stackdriver_exporter
```
Should be:
```
from opencensus.ext.stackdriver import trace_exporter as stackdriver_exporter
```

#### 3. Packages aren't referenced
I think it would be help to provide e.g. `requirements.txt`:
```
grpcio==1.19.0
opencensus==0.3.1
opencensus-ext-stackdriver==0.1.1
```
#### 4. Application Default Credentials aren't explained
The code requires credentials to run. Perhaps this is explained in the codelab but it would be trivial (and helpful) to reiterate guidance to
* Create a service account and a key
* Assign the service account the role: Cloud Trace Agent (roles/cloudtrace.agent)
* Reference the key using `export GOOGLE_APPLICATION_CREDENTIALS=/path/to/key`

#### 5. No Monitoring

Python is deficient in support for Monitoring. IIUC Stackdriver Trace is supported, for example but Stackdriver Monitoring is not. The documentation appears to have default references to Monitoring but this would be confusing to developers new to OpenCensus.

Recommend: Remove Monitoring references until available.

**Comment by odeke-em** [comment]
Thank you for this report @DazWilkin!

The imports are different because OpenCensus Python just recently radically changed the repository structure in https://github.com/census-instrumentation/opencensus-python/pull/550 about 24 days ago.

/cc @reyang @c24t @mayurkale22 could y'all please fix this and make updates to the website as well (or consolidate examples and tutorials) whenever you make breaking changes? Or perhaps pin a version of OpenCensus-Python so that the code stays stable as per @DazWilkin's suggestion 3 

@DazWilkin perhaps that might help solve the problem?

>4. Application Default Credentials aren't explained

@DazWilkin I am not inclined personally to explain and add ADCs. In the past I did that and folks complained that the docs seemed to require a lot of setup so delegated that to the codelab https://opencensus.io/codelabs/stackdriver/

Points 1 and 2, I'll defer to the OpenCensus Python team.

Thanks!
